# Generated by Django 4.0.4 on 2022-10-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('edad', models.PositiveIntegerField(default=0)),
                ('fecha_nacimiento', models.DateField()),
                ('nui', models.BigIntegerField(max_length=10)),
                ('fecha_inicio_tratamiento', models.DateField()),
                ('Seguro_funebre', models.BooleanField(default=False)),
                ('nucleo_familiar', models.CharField(max_length=45)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'otro')], default='F', max_length=1)),
                ('fecha_ingreso', models.DateField()),
                ('numero_telefonico', models.BigIntegerField(max_length=10)),
                ('correo_electronico', models.CharField(max_length=45)),
                ('historia_clinica', models.TextField(blank=True, null=True)),
                ('direccion_residencia', models.CharField(max_length=45)),
                ('nivel_educativo', models.CharField(max_length=45)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sueños',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente_x_sueños',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientexfamiliar.paciente')),
                ('id_sueño', models.ManyToManyField(to='pacientexfamiliar.sueños')),
            ],
        ),
    ]
