# Generated by Django 4.0.4 on 2022-10-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientexfamiliar', '0004_alter_paciente_numero_telefonico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero_telefonico',
            field=models.CharField(max_length=10),
        ),
    ]
