# Generated by Django 3.2 on 2022-10-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('pathology_type', models.CharField(max_length=50, verbose_name='tipo de pathology')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre')),
                ('time_pathology', models.DateField(blank=True, null=True, verbose_name='Tiempo de la patalogia')),
                ('condition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('cycle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciclo')),
            ],
        ),
    ]
