# Generated by Django 3.2 on 2022-10-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('state_exam', models.CharField(max_length=50, null=True, verbose_name='Estado del examen')),
                ('history_exam', models.CharField(max_length=50, null=True, verbose_name='Historia del examen')),
                ('reading_test', models.CharField(max_length=50, null=True, verbose_name='Lectura del examen')),
                ('exam_date', models.DateField(null=True, verbose_name='Fecha del examen')),
                ('number_of_exams', models.IntegerField(null=True, verbose_name='Numero de exams')),
            ],
        ),
    ]
