# Generated by Django 3.2 on 2022-10-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('medication_name', models.CharField(max_length=50, null=True, verbose_name='nombre del medicine')),
                ('amount', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('medication_formula', models.CharField(max_length=50, null=True, verbose_name='nombre del medicine')),
            ],
        ),
    ]
