# Generated by Django 4.0.4 on 2022-10-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientexfamiliar', '0002_estado_paciente_x_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero_telefonico',
            field=models.IntegerField(max_length=10),
        ),
    ]
