# Generated by Django 4.0.4 on 2022-10-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientexfamiliar', '0006_alter_paciente_numero_telefonico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('nit', models.BigIntegerField(max_length=10)),
                ('numero_telefonico', models.BigIntegerField(max_length=10)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente_x_eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('id_eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientexfamiliar.eps')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientexfamiliar.paciente')),
            ],
        ),
    ]
